language: node_js

node_js:
  - "7"
  - "8"

install:
  - npm install
  - npm install -g codecov

after_success:
  - codecov --token=7efdacde-d618-4028-9596-a4aec3733911

notifications:
  email:
    recipients:
      - alk03073135@gmail.com
    on_success: always
    on_failure: always